pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Installing frontend dependencies...'
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                echo 'Building frontend...'
                sh 'ng build --prod'
            }
        }

        stage('Test') {
            steps {
                echo 'Running frontend tests...'
                sh 'ng test --watch=false'
            }
        }
    }
}