pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building backend...'
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                echo 'Running backend tests...'
                sh 'mvn test'
            }
        }
    }
}