spring.application.name=api-gateway
server.port=8089


# ==================== EUREKA ====================
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==================== CORS ====================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# ==================== LOGGING ====================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG


# ==================== DOCKER (uncomment + comment above when running in Docker) ====================
# eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
