# 1. Identification du Service
spring.application.name=blog-service
# Port différent de communication (8085) pour éviter les erreurs "Port already in use"
server.port=8087

# 2. Configuration de la Base de Données (MySQL)
# J'ai utilisé 'blog_db' pour que tes articles soient indépendants du reste
spring.datasource.url=jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Configuration Eureka (Pour l'enregistrement sur le serveur de Badr)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true