#Server
spring.application.name=ApiGateway
server.port=8089


# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#GATEWAY
# Configuration des logs - une propri�t� par ligne
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
# 2. Activer la d�couverte des microservices
spring.cloud.gateway.discovery.locator.enabled=true


