# ==================== SERVICE INFO ====================
spring.application.name=api-gateway
server.port=8089

# ==================== CONFIG SERVER ====================
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false

# ==================== DOCKER ====================
# spring.config.import=configserver:http://config-server:8888